### ISSUE TITLE
Building master branch fails (on a prestine environment)

### ISSUE THREAD

**Issue by adinapoli** [slamdata/purescript-echarts#5]
Hello guys,

I have tried to build the library (as downloaded from github) doing:

```
pulp dep update
pulp build
```

The latter command fails with:

```
☁  purescript-echarts [master] pulp build
* Building project in /Users/adinapoli/programming/purescript/purescript-echarts
Multiple errors:

Error at bower_components/purescript-integers/src/Data/Int.purs line 31, column 1 - line 37, column 1:
Error in module Data.Int
Unknown type class 'Semiring'

Error at bower_components/purescript-integers/src/Data/Int.purs line 37, column 1 - line 41, column 1:
Error in module Data.Int
Unknown type class 'ModuloSemiring'

Error at bower_components/purescript-integers/src/Data/Int.purs line 41, column 1 - line 44, column 1:
Error in module Data.Int
Unknown type class 'Ring'
```

Any idea of what I'm doing wrong?
Thanks!
Alfredo

**Comment by garyb** [comment]
It looks like you need to update your compiler, the `Semiring` hierarchy was added to the prelude a little while back.

**Comment by adinapoli** [comment]
Makes sense, thanks!

**Comment by adinapoli** [comment]
Update: Sorry for being stupid, but when you say update your compiler, did you mean the `psc` executable alone? I did upgrade it, but it didn't make any change. I did only installed `purescript` in a sandbox (with `cabal install purescript`), moved `psc` into my `.cabal/bin` folder and that's it. Is there any other special operation I need to perform?

**Comment by garyb** [comment]
That's odd, what do you get from `psc --version`? The `Semiring` stuff was added in 0.6.8 so if it's later than that it should definitely be working.

**Comment by garyb** [comment]
Ah, you might need to copy `psc-make` over too, if you only did `psc`.

**Comment by adinapoli** [comment]
Ah! for some reason cabal was installing `0.6.7.x`, I'm currently installing `0.6.9` and then I will give it a spin. Thanks for the patience!

**Comment by adinapoli** [comment]
Great, it worked! Thanks a lot!

**Comment by garyb** [comment]
Glad to hear it :smile:
