### ISSUE TITLE
Deprecated dependency

### ISSUE THREAD

**Issue by mschristiansen** [slamdata/purescript-echarts#53]
`purescript-dom` is now deprecated and it could seem that `purescript-eff` will be deprecated in favor of `purescript-effect`. Any plans to update?

**Comment by mschristiansen** [comment]
Just updated another package to use the `purescript-web` packages and `purescript-effect`, so could give it a try here as well. Interested in a pull request?

**Comment by cryogenian** [comment]
That would be awesome, thank you

**Comment by mschristiansen** [comment]
I ran into some phantom types, which I wasn't quite prepared for and also don't currently need echarts in my Purescript app. Sorry...
